name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTBiMmMzOGItMzRkYS00YjIzLWFiMzUtNjA3YzM2NWFjOTgyIiwidGVuYW50X2lkIjoiZWM5OGQ5ZDVhZTE4ZTBhZGE0M2MyYzRjNDU3MDU0ZmI0NTk2NzI4MWI1ZTEwZTM5MmQ1ZmY4Nzk2MDgxMjFmZCIsImludGVybmFsX3NlY3JldCI6IjFiNzcxMDQ3LTQ5NzktNDE0My1iNjc2LTg3MTY3ZjViZjhmNSJ9.aXPc9DPjrBUbfOS27TBH1bTOqfEcFSrT6JN9GQRnsL0"
JWT_SECRET ="secret"